// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uetpjqqxynchsfltdtox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldHBqcXF4eW5jaHNmbHRkdG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjczNzIsImV4cCI6MjA2OTcwMzM3Mn0.FNIdIp2FK4VsOJ_HRQrXELNMl9uRwbTxgYp52b8Kg_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});